---
title: "Noramlizing Tokens"
author: "Grace Lawley"
date: "8/4/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("R/01_data-processing/childes/00_setup.R")
source("R/01_data-processing/childes/normalization/norm_fxns.R")
```

Loading filtered utterances, raw utterances, and processed cmu-dict
```{r loading_data}
fil_in_path <- here("data/processed/childes/all_filtered-utterances.csv")
cmu_in_path <- here("data/processed/ref-corpora/cmu-dict-0.7b_proc.csv")

fil_utts <- read_csv(fil_in_path) # filtered utterances
cmu <- read_csv(cmu_in_path) # processed cmu-dict
```


Removing unneeded columns from `utts` with corpora metadata and only keeping the `utterance` column. Then tokenizing the utterances with tokens being split on **white space**
```{r}
tokens <- fil_utts %>% 
  select(corpus, child, utterance) %>% 
  unnest_tokens(output = word, input = utterance, token = "regex", 
                pattern = "[:space:]", to_lower = FALSE) 
```


```{r}
types <- tokens %>% 
  distinct(word)
  
word_mappings <- types %>% 
  mutate(mapping = map_chr(word, plus_norm, cmu$entry),
         mapping = map_chr(mapping, phrase_norm),
         mapping = map_chr(mapping, capitals_norm),
         mapping = map_chr(mapping, contracts_exceptions_expand),
         mapping = map_chr(mapping, contracts_general_expand),
         mapping = map_chr(mapping, code_wds_drop))
```

```{r}
word_mappings %>% 
  count(mapping == word) 
```


```{r}
tokens_normed <- tokens %>% 
  left_join(word_mappings, by = "word") %>% 
  select(-word, word = mapping)
  
  
  
  # left_join(word_mappings, by = "word") %>% 
  # mutate(word = ifelse(is.na(mapping), word, mapping)) %>% 
  # select(-mapping)


tokens_normed <- tokens_normed %>% 
  unnest_tokens(output = word, input = word, token = "regex",
                pattern = "[:space:]")
```



```{r}

# erpa_in_path <- here("data/processed/erpa_tokens.csv")
# erpa_in_path_2 <- here("data/processed/erpa_unsplit.csv")
# 
# erpa_proc <- read_csv(erpa_in_path)
# erpa_raw <- read_csv(erpa_in_path_2)

```






