---
title: "plotting fun'"
author: "Grace Lawley"
date: "8/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

tokens_unnormed <- read_csv("data/processed/childes/all_tokens_unnormed.csv")
tokens_normed <- read_csv("data/processed/childes/all_tokens_normed.csv")

```

```{r}
stats_unnormed <- tokens_unnormed %>% 
  select(corpus, child, sex, age, word) %>% 
  
  # calculate token count
  add_count(corpus, child, age) %>% 
  rename(unnormed_n_tokens = n) %>% 
  
  # calculate type count
  group_by(corpus, child, age) %>% 
  mutate(unnormed_n_types = n_distinct(word)) %>% 
  ungroup() %>% 
  
  # calculate ttr
  mutate(unnormed_ttr = unnormed_n_types/unnormed_n_tokens) %>% 
  
  # reorganizing
  select(-word) %>% 
  distinct(.keep_all = TRUE)
```

```{r}
stats_unnormed <- stats_unnormed %>% 
  rename(age_months = age) %>% 
  mutate(age_years = age_months/12,
         age_months_floor = floor(age_months),
         age_years_floor = floor(age_years))


stats_unnormed <- stats_unnormed %>% 
  mutate(corpus = as.factor(corpus),
         child = as.factor(child),
         age_months_floor = as.factor(age_months_floor),
         age_years_floor = as.factor(age_years_floor))
```

```{r}
longitudinal <- c("Braunwald", "Brown", "Kuczaj", "MacWhinney", "Weist")

stats_subset <- stats_unnormed %>% 
  filter(corpus %in% longitudinal)
```



```{r}
ggplot(stats_subset, aes(x = age_months_floor, y = unnormed_ttr,
                           group = child, color = child)) +
  geom_point(alpha = 0.5) +
  geom_line() + 
  guides(color = FALSE) +
  facet_grid(corpus ~ .)  

ggplot(stats_subset, aes(x = age_months_floor, y = unnormed_ttr,
                           group = child, fill = child)) +
  geom_col(position = "dodge") +
  guides(fill = FALSE) +
  facet_grid(corpus ~ .)  





  
ggplot(stats_unnormed, aes(x = age_months_floor, y = unnormed_ttr,
                           fill = child)) +
  geom_area(alpha = 0.5) +
  guides(fill = FALSE) +
  facet_grid(corpus ~ .) +
  theme_minimal()

```







```{r}
# # normed stats
# stats_normed <- tokens_normed %>% 
#   # calculate token count
#   add_count(corpus, child) %>% 
#   rename(normed_n_tokens = n) %>% 
#   
#   # calculate type count
#   group_by(corpus, child) %>% 
#   mutate(normed_n_types = n_distinct(word)) %>% 
#   ungroup() %>% 
#   
#   # calculate type-token ratio
#   mutate(normed_ttr = normed_n_types/normed_n_tokens) %>% 
#   
#   # reorganize
#   distinct(corpus, child, .keep_all = TRUE) %>% 
#   select(-word)
# 
# 
# 
# # joining both into one stats df
# stats_by_child <- stats_raw %>% 
#   left_join(stats_normed, by = c("corpus", "child"))
```
